### ISSUE TITLE
[RFC] 帮助文档从 GitHub Wiki 换成 VitePress 在线文档

### ISSUE THREAD

**Issue by zthxxx** [EstrellaXD/Auto_Bangumi#376]
### 背景 or 问题

`v3.0` 以及之前版本都使用 [GitHub Wiki](https://github.com/EstrellaXD/Auto_Bangumi/wiki) 形式组织文档内容，

众所周知，当文档内容逐渐多了之后，这在「阅读排版」、「目录索引」、「搜索查找」上的读文档体验都很差；

而且写文档也麻烦，不仅没有整体预览效果、没法 PR 多人协作，同时以 git submodule 的形式放在仓库也在切分支和 pull 时干扰日常开发了。

尤其面向来**看番的普通大众**来说，少了「搜索查找」确实更难在一堆文档中找到需要的答案了，

因此提议从 GitHub Wiki 换成 [VitePress](https://vitepress.dev) 在线文档，即是在线文档站、也能作为官网、也能直接放在 WebUI 中。

### 目标 & 方案简述

经过调整的 [VitePress](https://vitepress.dev) 文档效果基本能快速解决阅读排版、目录索引问题，搜索查找有插件支持，也因为在同仓库内，大家可以基于分支多人协作修改；
部署文档站后，四舍五入等于白送一个官网 👀；

**具体目标大概是：**
- `3.1` 的 wiki 移到仓库 `docs/` 目录下，增加 VitePress 配置
- 文档站首页设计一下板式，符合官网 Landing Page 的感觉
    - 首页加些直观的演示，最基础的参考：
        - https://mermaid.js.org
        - https://sli.dev
- 部署简单点，官网直接使用 GitHub Pages + CNAME + Cloudflare 部署
- 在 `3.1` 合并与发版之后，有 main / PR 的更新，CI 自动部署官网和对应 PR preview 页面

#### 改造阶段
整个改造有 4 个阶段：
- [x] 1)  在 `3.1-dev` 分支上仓库结构调整，配起 VitePress 架子；**【仅本地看效果】** (#370)
- [x] 2)  在 `3.1` 分支中更新 `3.0` 文档，调整排版等；**【本地 + Vercel Preview，给开发组看效果】** (#379)
- [x] 3)  手动部署官网，先上线 `3.0` 文档；**【Vercel Prod，手动部署官网】**
    - 申请域名、建立 Vercel Project、Cloudflare site
    - Vercel Project 授权开发组、绑定域名，
      手动上传部署 prod 模式作为官网
      (也可以绑定 git repo + `3.1-dev` 分支加 build 配置，前期也能 CI 上线官网)
- [ ] 4)   `3.1` 分支合并发版后，更新 `3.1` 的文档，同步调整 CI 流程 **【GitHub Pages 自动更新官网】**
    (记得更新原本的 wiki / README / blog 中的链接，都改成指向文档站的链接)
    - GitHub Actions 流程中增加 `main` 分支上有更新，就构建文档站，上传 `gh-pages` 做官网
    - Actions 中增加 PR 的 CI 中构建文档站，走 token 上传独立的 Vercel Preview 页面
      (也可以根据 paths 只检测 `docs/` 下的更新)
    - 去掉 Vercel 域名绑定，转为 CNAME 到 Cloudflare
    - GitHub 仓库的 details 中添加 Website

#### 仓库文档结构

```tree
.
├── README.md
└── docs
    ├── assets/
    ├── .vitepress
    │   ├── dist  
    │   └── cache  
    ├── XOXO/    # 实际各个文档目录/文件
    ├── OXOX.md  # 实际各个文档目录/文件
    ├── package.json
    ├── pnpm-lock.yaml
    └── node_modules
```

`.vitepress, package.json` 与实际各个文档平级，少一层 `src` 嵌套，但是配置文件和文档看着混在一起

#### Vercel Depoly CI Config

以下配置是对于第 3) 阶段中的
> 也可以绑定 git repo + `3.1-dev` 分支加 build 配置，前期也能 CI 上线官网

配置里绑定了  Git 仓库和分支，这样分支更新自动触发 Vercel 跑 CI 构建和部署 Preview； 
(Production 是在 Preview 更新后手动选择一个作为 Prod 环境，也可以配置为自动)

<details>
<img width="368" alt="image" src="https://github.com/EstrellaXD/Auto_Bangumi/assets/15135943/348d18f8-f02e-43de-81ed-0df3edbbbb5a">

<img width="500" alt="image" src="https://github.com/EstrellaXD/Auto_Bangumi/assets/15135943/8b9dfd0e-b9be-4314-923c-873e668cbe35">
</details>

如果是要对于 PR 做 Vercel 部署的话，在 GitHub 仓库里加 Vercel 就可以了

<details>
<img width="528" alt="image" src="https://github.com/EstrellaXD/Auto_Bangumi/assets/15135943/e67ad8b6-f073-40a9-898e-4b6814505cd4">
</details>

### 替代方案 & 对比

[**`Docusaurus`**](https://docusaurus.io)
- 生态最广，功能最齐全
- 面向二次开发更强大 (React)
- 但配置稍微麻烦，开箱即用性比 VitePress 麻烦
- 比较老派但默认视觉设计也老气，不够现代
> 大概是对现阶段用 Docusaurus 或 VitePress 都差不多

[**`Nextra`**](https://nextra.site)
- 新，生态不够多，功能还是齐全
- 基于 Next.js (React)
- 默认样式足够美观，你永远可以相信 vercel 的设计
- 开箱即用性比 VitePress 稍微麻烦一点，但也在可算较好的范围
> 除了是 react 体系，和开发组技术栈不同外，没有别的问题了
